mar-file-system/GUFI

scripts/gufi_find
scripts/gufi_ls
scripts/gufi_stats

os.path.join arguments that are not the first should not begin with path separators
- everything left of the rightmost slash is dropped
This affects`gufi_find`, `gufi_ls`, and `gufi_stats`
Fixes an issue mentioned in #8.

Fixed bug with os.path.join usage

---

scripts/gufi_find

Fixes #11 
Use `-fprint` instead of `-fprintf` because there is no format to provide.

Rename gufi_find -o to -fprint

---

CMakeLists.txt

Default: `gufi-${GUFI_VERSION}.${ARCH}.rpm`
Server: `gufi_server-${GUFI_VERSION}.${ARCH}.rpm`
Client: `gufi_client-${GUFI_VERSION}.${ARCH}.rpm`
Fixes #9

Renamed generated RPMs

---

contrib/make/test
include/bf.h
scripts/gufi_config.py
scripts/gufi_ls
src/bf.c
src/dbutils.c
src/gufi_dir2index.c
src/gufi_dir2trace.c
src/gufi_query.c
src/template_db.c
test/CMakeLists.txt
test/runbfwi
test/verifyknowntree

Fixes #8 
updated non-recursive queries to use formatting functions
fixed depth of non-recursive queries
recursive ls
indexing `/a/b/c` to `/q/r/s` now goes to `/q/r/s`, where `s` contains `c`'s immediate contents.

gufi_ls updates

---

CMakeLists.txt
contrib/travis/build_and_test.sh
contrib/travis/centos7.sh
contrib/travis/suse12.3.sh
scripts/CMakeLists.txt
scripts/gufi_jail

Fixed error with `exec` call
~~Added tests to make sure commands that should pass do pass.~~
~~Added tests to check obvious attempts to circumvent `gufi_jail`.~~
Tests are preserved in the commits, but have been removed for now. They require the config file to be installed before testing, and some of the test machines do not like `sudo`.

gufi_jail updates

---

README.md
src/gufi_dir2index.c
src/gufi_dir2trace.c
test/runbfwi

Now, instead of calling `gufi_dir2trace -o <prefix> <src>`, call `gufi_dir2trace <src> <prefix>`.

gufi_dir2trace prefix argument

---

scripts/gufi_stats

non-cumulative query uses the old query
updated to use pentries
cumulative query uses summary.totsize instead of sum(entries.size)

Update gufi_stats total-filesize query

---

include/bf.h
include/dbutils.h
scripts/gufi_find
src/dbutils.c
src/gufi_query.c
src/querydb.c
src/querydbn.c

similar to GNU find -printf
not implemented: %A, %C, %F, %T, %Y, and %Z
automatically terminates with newline
added starting_point SQLite function to implement %H and %P
gufi_find now queries most rows from summary and entries instead of
selecting only what is needed
renamed --num_results to --num-results

Added gufi_find -printf

---

contrib/make_testindex.cpp
contrib/verifytraceintree.cpp
include/bf.h
include/trace.h
include/utils.h
src/bfmi.c
src/bfti.c
src/bfwreaddirplus2db.c
src/dbutils.c
src/dfw.c
src/gufi_dir2index.c
src/gufi_dir2trace.c
src/gufi_trace2index.c
src/trace.c
src/utils.c
test/googletest/trace.cpp
test/googletest/utils.cpp

key-value pairs are stored as arrays of pairs delimited by \x1f:
```<key>\x1f<value>\x00<key>\x1f<value>\x00```...
```struct work``` ```xattrs``` has been replaced by ```xattrs_len```, and ```xattr``` has been renamed ```xattrs```.
Added ```get_xattr_value``` function to extract value from ```struct work``` ```xattrs```, given a key.

Change pullxattrs to be able to read as many xattrs as can fit the buffer

---

include/bf.h
src/bf.c
src/gufi_query.c

Th ```-K``` SQL command is called once when setting up aggregation as an alternative to using ```-I``` to create the final aggregation table. This allows for more flexibility when the final output columns are not the same as the intermediate columns.
```gufi_query``` will fall back to ```-I``` if ```-K``` is not provided.

Alternate Aggregate Table CREATE SQL

---

include/OutputBuffers.h
src/OutputBuffers.c
src/debug.c
src/gufi_query.c
test/googletest/CMakeLists.txt
test/googletest/OutputBuffers.cpp

A global mutex for a `struct OutputBuffers` creates contention between threads writing to their own `struct OutputBuffer`, so `struct OutputBuffer` was given a mutex. However, if no output file prefix is provided, all of the `struct OutputBuffer`s will write to the same file (`stdout`), which is a race condition. A global mutex is created if no output file prefix is provided to prevent this.
<del>`gufi_dir2trace` still has the race condition
- writes are done directly to the output file, not `OutputBuffers` - need to change
- simply using mutexes requires wrapping the entire loop of processdir, which causes too much contention
- See #54 and #55 
</del>
`OutputBuffer` and `OutputBuffers` api rework
- `OutputBuffer_flush` no longer locks since it does not care who else is accessing the file …

Reduce struct OutputBuffers contention

---

include/bf.h
src/gufi_query.c

makes parsing cumulative times easier
reuse `-j` from gufi_stat

print gufi_query cumulative timestamps in terse format

---

contrib/deps/sqlite-autoconf-3270200.patch
contrib/deps/sqlite3.sh

In a scenario where the unrolled-up or rolled-up GUFI index is large, GUFI's performance is effected by large number of opens. This patch aims to reduce open overhead by modifying SQLite to incorporate GUFI's design principles.

GUFI open optimization patch

---

contrib/performance/collect_performance.sh

Commits before commit 1a6137e "group debug macros together in cmake" use CUMULATIVE_TIMES instead of PRINT_CUMULATIVE_TIMES.

Collect performance for PRINT_CUMULATIVE_TIMES and CUMULATIVE_TIMES

---

contrib/performance/performance_pkg/extraction/gufi_query/README.md

Combined 86d3d0e..a9a1ef7, 831705f..6bde154, and 8480cd1..ea4c148 into 1 
Documented select * segfault issue in early commits
Updated range of undocumented commits

gufi_query commit table update

---

docs/latex/sections/deploy.tex
docs/latex/sections/user_env.tex
scripts/gufi_config.py
scripts/gufi_find
scripts/gufi_getfattr
scripts/gufi_ls
scripts/gufi_stat
scripts/gufi_stats
test/unit/python/test_gufi_config.py

Can use an env var to change the location of gufi config used by tools like gufi_stats. Useful when running without root.

small change so folks can test gufi without needing a config at /etc

---

docs/latex/sections/deploy.tex
scripts/gufi_common.py
scripts/gufi_config.py
scripts/gufi_find
scripts/gufi_getfattr
scripts/gufi_ls
scripts/gufi_stat
scripts/gufi_stats
test/regression/gufi_find.expected
test/regression/gufi_find.sh.in
test/regression/gufi_getfattr.expected
test/regression/gufi_getfattr.sh.in
test/regression/gufi_ls.expected
test/regression/gufi_ls.sh.in
test/regression/gufi_stat.expected
test/regression/gufi_stat.sh.in
test/regression/gufi_stats.expected
test/regression/gufi_stats.sh.in

Two small changes here:
1. I always get confused when I don't have a config in /etc/GUFI and I'm not running my modified version which allows configurable values of gufi config path. This change prints an explanatory error message so it will be clear when other people (including myself) run without a gufi config in /etc/GUFI
2. Added verbose mode to gufi_stats to print the actual gufi_query. Useful for debugging and for people learning how it works.

Verbose stats and verbose error message

---

include/utils.h
src/gufi_dir2index.c
src/gufi_dir2trace.c
src/gufi_index2dir.c
src/gufi_treesummary.c
src/parallel_cpr.c
src/utils.c
test/unit/googletest/utils.cpp.in

descend() in utils.c includes an unnecessary parameter, trie_t *skip_names.
Every caller of descend() passes in this item from a struct input which is already passed as a parameter to descend().
Thus, descend()'s signature can be simplified by removing this extra parameter.

remove unnecessary parameter from descend()

---

include/compress.h
src/compress.c
test/unit/googletest/compress.cpp

Currently errors in zlib's uncompress() function are ignored, which in the worst case could mean continuing to run the program with memory corruption or unexpected results.
There are two error conditions that can be encountered. This patch makes the program abort if it encounters either.
- Running out of memory: while this is a valid condition and could be handled, the program is unlikely to be able to make any useful progress if it cannot allocate memory, and aborting means we don't have to add error handling code for this case.
- Invalid or corrupt data: because this program is the source of all data that it uncompresses, it should never encounter an invalid or corrupt zlib stream. If it does, that indicates a memory bug, and panicking is the safest course of action.
Because …

handle errors in zlib uncompress()

---

include/utils.h
src/gufi_dir2index.c
src/utils.c

This dumps the memory RSS high water mark for gufi_dir2index when running on linux with -DDEBUG.
The intention is to make it easier to identify improvements or regressions in memory usage since now no external tools are needed to get peak usage for a run.

dump memory high water mark for gufi_dir2index

---

.gitignore
include/bf.h
src/gufi_dir2index.c
src/gufi_dir2trace.c
src/utils.c

Pathname resolution has a significant overhead during
GUFI indexing. Using the _at variant of stat(2) when processing
files means less work is required to resolve the paths.
Profiling GUFI runs with flamegraphs suggests that this is an
effective change to reduce the overhead of pathname resolution.
I observed the time spent resolving names go from ~ 14% using
lstat(2) down to ~ 6% using fstatat(2), in one example run on an
NFS filestystem with approx. 450,000 files.
----
Example flamegraphs attached, zoom in on `vfs_statx -> filename_lookup` under `process_work`

Use fstatat(2) instead of lstat(2) when processing files during indexing

---

include/BottomUp.h
include/utils.h
src/BottomUp.c
src/parallel_rmr.c
src/utils.c

The first two commits are changes that reduce the size of `struct BottomUp`:
- removes a mostly unused embedded `struct stat` 
- removes two fixed 4 KiB buffers, one of which is always unused for parallel_rmr, in favor of dynamically allocating a buffer for pathnames that is only as large as needed
Overall this reduces the size of `struct BottomUp` from 8504 B to 184 B and seems to make a significant difference for parallel_rmr.
The third commit in the series modifies the logic of `descend_to_bottom()` in BottomUp.c to not format pathnames for non-directory nodes unless those nodes are actually processed. This removes an allocation for all the non-dir nodes in cases where those nodes are not processed.

changes for better memory usage in users of BottomUp (parallel_rmr, etc)
